let mySprite2: Sprite = null
scene.setBackgroundColor(6)
tiles.setCurrentTilemap(tilemap`level1`)
let mySprite = sprites.create(img`
    ......eee...eee...............
    ......e3e...e3e...............
    ......eeeeeeeee...............
    ......eeeeeeeee...............
    ......eddddddde...............
    ......e18ddd81e...............
    ......eddddddde...............
    ......eddddddde...............
    ......eeeeeeeee...............
    ...eeeeeeeeeeeeeee............
    ...deeeeeeeeeeeeed............
    ...dd.deeeeeeed.dd............
    ...dd.ddeeeeedd.dd............
    ...dd.dddeeeddd.dd............
    ...dd.ddddedddd.dd............
    ...dd.ddddddddd.dd............
    ...dd.ddddddddd.dd............
    ...dd.ddddddddd.dd............
    ...dd.ddddddddd.dd............
    ...dd.eeeeeeeee.dd............
    ...dd.ee1eee1ee.dd............
    ....d.dee111eed.d.............
    ......dd1eee1dd...............
    ......dd.eee.dd...............
    ......dd..e..dd...............
    ......dd.....dd...............
    ......dd.....dd...............
    ......dd.....dd...............
    ......dd.....dd...............
    ......ddd....ddd..............
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
mySprite.setStayInScreen(true)
scene.cameraFollowSprite(mySprite)
tiles.placeOnRandomTile(mySprite, sprites.swamp.swampTile0)
for (let index = 0; index < 10; index++) {
    mySprite2 = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Enemy)
}
